//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.CRM15.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
     using System.ComponentModel.DataAnnotations;
    public partial class sysUserInfoView
    {
     
    
        public int uID { get; set; }
        public string uLoginName { get; set; }
        public string uLoginPWD { get; set; }
        public string uRealName { get; set; }
        public string uTelphone { get; set; }
        public string uMobile { get; set; }
        public string uEmial { get; set; }
        public string uQQ { get; set; }
        public int uGender { get; set; }
        public int uStatus { get; set; }
        public int uCompanyID { get; set; }
        public Nullable<int> uDepID { get; set; }
        public Nullable<int> uWorkGroupID { get; set; }
        public string uRemark { get; set; }
        public int uCreatorID { get; set; }
        public System.DateTime uCreateTime { get; set; }
        public Nullable<int> uUpdateID { get; set; }
        public System.DateTime uUpdateTime { get; set; }
    
        public virtual sysOrganStructView sysOrganStruct { get; set; }
        public virtual sysOrganStructView sysOrganStruct1 { get; set; }
        public virtual sysOrganStructView sysOrganStruct2 { get; set; }
        public virtual ICollection<sysUserInfo_RoleView> sysUserInfo_Role { get; set; }
        public virtual ICollection<wfRequestFormView> wfRequestForm { get; set; }
    }
}
