//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.CRM15.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JKCRMEntities : DbContext
    {
        public JKCRMEntities()
            : base("name=JKCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysFunction> sysFunction { get; set; }
        public DbSet<sysKeyValue> sysKeyValue { get; set; }
        public DbSet<sysMenus> sysMenus { get; set; }
        public DbSet<sysOrganStruct> sysOrganStruct { get; set; }
        public DbSet<sysPermissList> sysPermissList { get; set; }
        public DbSet<sysRole> sysRole { get; set; }
        public DbSet<sysUserInfo> sysUserInfo { get; set; }
        public DbSet<sysUserInfo_Role> sysUserInfo_Role { get; set; }
        public DbSet<wfProcess> wfProcess { get; set; }
        public DbSet<wfRequestForm> wfRequestForm { get; set; }
        public DbSet<wfWork> wfWork { get; set; }
        public DbSet<wfWorkBranch> wfWorkBranch { get; set; }
        public DbSet<wfWorkNodes> wfWorkNodes { get; set; }
    }
}
