//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.CRM15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysKeyValue
    { 
        public sysKeyValue()
        {
            this.sysOrganStruct = new HashSet<sysOrganStruct>();
            this.sysRole = new HashSet<sysRole>();
            this.wfProcess = new HashSet<wfProcess>();
            this.wfRequestForm = new HashSet<wfRequestForm>();
            this.wfRequestForm1 = new HashSet<wfRequestForm>();
            this.wfWorkNodes = new HashSet<wfWorkNodes>();
            this.wfWorkNodes1 = new HashSet<wfWorkNodes>();
        }
    
        public int KID { get; set; }
        public int ParentID { get; set; }
        public int KType { get; set; }
        public string KName { get; set; }
        public string Kvalue { get; set; }
        public string KRemark { get; set; }
    
        public virtual ICollection<sysOrganStruct> sysOrganStruct { get; set; }
        public virtual ICollection<sysRole> sysRole { get; set; }
        public virtual ICollection<wfProcess> wfProcess { get; set; }
        public virtual ICollection<wfRequestForm> wfRequestForm { get; set; }
        public virtual ICollection<wfRequestForm> wfRequestForm1 { get; set; }
        public virtual ICollection<wfWorkNodes> wfWorkNodes { get; set; }
        public virtual ICollection<wfWorkNodes> wfWorkNodes1 { get; set; }
    }
}
