//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.CRM15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysMenus
    { 
        public sysMenus()
        {
            this.sysFunction = new HashSet<sysFunction>();
            this.sysPermissList = new HashSet<sysPermissList>();
        }
    
        public int mID { get; set; }
        public int mParentID { get; set; }
        public string mName { get; set; }
        public string mUrl { get; set; }
        public string mArea { get; set; }
        public string mController { get; set; }
        public string mAction { get; set; }
        public int mSortid { get; set; }
        public int mStatus { get; set; }
        public string mPicname { get; set; }
        public int mLevel { get; set; }
        public string mExp1 { get; set; }
        public Nullable<int> mExp2 { get; set; }
        public int mCreatorID { get; set; }
        public System.DateTime mCreateTime { get; set; }
        public Nullable<int> mUpdateID { get; set; }
        public System.DateTime mUpdateTime { get; set; }
    
        public virtual ICollection<sysFunction> sysFunction { get; set; }
        public virtual ICollection<sysPermissList> sysPermissList { get; set; }
    }
}
