//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.CRM15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysUserInfo_Role
    { 
        public int urID { get; set; }
        public int uID { get; set; }
        public int rID { get; set; }
    
        public virtual sysRole sysRole { get; set; }
        public virtual sysUserInfo sysUserInfo { get; set; }
    }
}
