//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.CRM15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wfWorkNodes
    { 
        public wfWorkNodes()
        {
            this.wfProcess = new HashSet<wfProcess>();
            this.wfWorkBranch = new HashSet<wfWorkBranch>();
            this.wfWorkBranch1 = new HashSet<wfWorkBranch>();
        }
    
        public int wfnID { get; set; }
        public int wfID { get; set; }
        public int wfnOrderNo { get; set; }
        public int wfNodeType { get; set; }
        public string wfNodeTitle { get; set; }
        public string wfnBizMethod { get; set; }
        public decimal wfnMaxNum { get; set; }
        public int wfnRoleType { get; set; }
        public Nullable<int> wfnExt1 { get; set; }
        public string wfnExt2 { get; set; }
        public int fCreatorID { get; set; }
        public System.DateTime fCreateTime { get; set; }
        public Nullable<int> fUpdateID { get; set; }
        public Nullable<System.DateTime> fUpdateTime { get; set; }
    
        public virtual sysKeyValue sysKeyValue { get; set; }
        public virtual sysKeyValue sysKeyValue1 { get; set; }
        public virtual ICollection<wfProcess> wfProcess { get; set; }
        public virtual wfWork wfWork { get; set; }
        public virtual ICollection<wfWorkBranch> wfWorkBranch { get; set; }
        public virtual ICollection<wfWorkBranch> wfWorkBranch1 { get; set; }
    }
}
