//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.CRM15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wfWorkBranch
    { 
        public int wfbID { get; set; }
        public int wfnID { get; set; }
        public string wfnToken { get; set; }
        public int wfNodeID { get; set; }
        public int fCreatorID { get; set; }
        public System.DateTime fCreateTime { get; set; }
        public Nullable<int> fUpdateID { get; set; }
        public System.DateTime fUpdateTime { get; set; }
    
        public virtual wfWorkNodes wfWorkNodes { get; set; }
        public virtual wfWorkNodes wfWorkNodes1 { get; set; }
    }
}
